doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            FeedBundle:
                is_bundle: true
                type: annotation
                dir: 'Entity'
                prefix: 'FeedBundle\Entity'
                alias: FeedBundle
        metadata_cache_driver:
            type: service
            id: doctrine.cache.memcached
        query_cache_driver:
            type: service
            id: doctrine.cache.memcached
        result_cache_driver:
            type: service
            id: doctrine.cache.memcached

services:
    memcached.doctrine:
        class: Memcached
        factory: Symfony\Component\Cache\Adapter\MemcachedAdapter::createConnection
        arguments:
            - '%env(MEMCACHED_DSN)%'
            - PREFIX_KEY: 'my_app_doctrine'

    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - ['setMemcached', ['@memcached.doctrine']]
