version: '3.1'

services:

  php-fpm:
    build: docker
    container_name: 'php'
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - 7777:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

