branch-defaults:
  lesson-25:
    environment: symfony-framework-course-dev
    group_suffix: null
global:
  application_name: symfony-framework-course
  branch: null
  default_ec2_keyname: eb2
  default_platform: PHP 7.4 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
