# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        exclude: '../src/Controller/Common/*'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    doctrineMigrationDiffListener:
        class: App\Symfony\MigrationEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    monolog.formatter.app_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%level_name%%]: [%%datetime%%] %%message%%\n"

    App\Service\AsyncService:
        calls:
            - ['registerProducer', [!php/const App\Service\AsyncService::ADD_FOLLOWER, '@old_sound_rabbit_mq.add_follower_producer']]
            - ['registerProducer', [!php/const App\Service\AsyncService::PUBLISH_TWEET, '@old_sound_rabbit_mq.publish_tweet_producer']]
            - ['registerProducer', [!php/const App\Service\AsyncService::SEND_NOTIFICATION, '@old_sound_rabbit_mq.send_notification_producer']]
            - ['registerProducer', [!php/const App\Service\AsyncService::UPDATE_FEED, '@old_sound_rabbit_mq.update_feed_producer']]

    App\Client\StatsdAPIClient:
        arguments:
            - graphite
            - 8125
            - my_app

    App\Consumer\UpdateFeedConsumer\Consumer0:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_0'

    App\Consumer\UpdateFeedConsumer\Consumer1:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_1'

    App\Consumer\UpdateFeedConsumer\Consumer2:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_2'

    App\Consumer\UpdateFeedConsumer\Consumer3:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_3'

    App\Consumer\UpdateFeedConsumer\Consumer4:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_4'

    App\Consumer\UpdateFeedConsumer\Consumer5:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_5'

    App\Consumer\UpdateFeedConsumer\Consumer6:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_6'

    App\Consumer\UpdateFeedConsumer\Consumer7:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_7'

    App\Consumer\UpdateFeedConsumer\Consumer8:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_8'

    App\Consumer\UpdateFeedConsumer\Consumer9:
        class: App\Consumer\UpdateFeedConsumer\Consumer
        arguments:
            $key: 'update_feed_9'
